// ──────────────────────────────────────────────
// TradeMind — Supabase TypeScript Types
// Auto-generated by supabase cli: supabase gen types typescript --linked
// This is a manual scaffold matching our schema
// ──────────────────────────────────────────────

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          role: 'USER' | 'ADMIN';
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name: string;
          role?: 'USER' | 'ADMIN';
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          role?: 'USER' | 'ADMIN';
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      broker_connections: {
        Row: {
          id: string;
          user_id: string;
          broker_id: string;
          broker_client_id: string;
          label: string;
          auth_type: string;
          access_token: string;
          refresh_token: string | null;
          api_key: string | null;
          api_secret: string | null;
          token_expires_at: string | null;
          status: string;
          last_synced_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          broker_id: string;
          broker_client_id: string;
          label?: string;
          auth_type: string;
          access_token: string;
          refresh_token?: string | null;
          api_key?: string | null;
          api_secret?: string | null;
          token_expires_at?: string | null;
          status?: string;
          last_synced_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          broker_id?: string;
          broker_client_id?: string;
          label?: string;
          auth_type?: string;
          access_token?: string;
          refresh_token?: string | null;
          api_key?: string | null;
          api_secret?: string | null;
          token_expires_at?: string | null;
          status?: string;
          last_synced_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "broker_connections_user_id_fkey";
            columns: ["user_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      broker_profiles: {
        Row: {
          id: string;
          user_id: string;
          broker_connection_id: string;
          user_name: string;
          email: string | null;
          phone: string | null;
          exchanges_enabled: string[];
          user_type: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          broker_connection_id: string;
          user_name: string;
          email?: string | null;
          phone?: string | null;
          exchanges_enabled?: string[];
          user_type?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          broker_connection_id?: string;
          user_name?: string;
          email?: string | null;
          phone?: string | null;
          exchanges_enabled?: string[];
          user_type?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "broker_profiles_broker_connection_id_fkey";
            columns: ["broker_connection_id"];
            referencedRelation: "broker_connections";
            referencedColumns: ["id"];
          },
        ];
      };
      account_balances: {
        Row: {
          id: string;
          user_id: string;
          broker_connection_id: string;
          available_cash: number;
          used_margin: number;
          total_collateral: number;
          payin_amount: number;
          payout_amount: number;
          currency: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          broker_connection_id: string;
          available_cash?: number;
          used_margin?: number;
          total_collateral?: number;
          payin_amount?: number;
          payout_amount?: number;
          currency?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          broker_connection_id?: string;
          available_cash?: number;
          used_margin?: number;
          total_collateral?: number;
          payin_amount?: number;
          payout_amount?: number;
          currency?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "account_balances_broker_connection_id_fkey";
            columns: ["broker_connection_id"];
            referencedRelation: "broker_connections";
            referencedColumns: ["id"];
          },
        ];
      };
      portfolio_holdings: {
        Row: {
          id: string;
          user_id: string;
          broker_connection_id: string;
          isin: string | null;
          tradingsymbol: string;
          exchange: string;
          quantity: number;
          authorized_quantity: number | null;
          average_price: number;
          current_price: number;
          pnl: number;
          day_change_percentage: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          broker_connection_id: string;
          isin?: string | null;
          tradingsymbol: string;
          exchange: string;
          quantity: number;
          authorized_quantity?: number | null;
          average_price: number;
          current_price: number;
          pnl?: number;
          day_change_percentage?: number;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          broker_connection_id?: string;
          isin?: string | null;
          tradingsymbol?: string;
          exchange?: string;
          quantity?: number;
          authorized_quantity?: number | null;
          average_price?: number;
          current_price?: number;
          pnl?: number;
          day_change_percentage?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "portfolio_holdings_broker_connection_id_fkey";
            columns: ["broker_connection_id"];
            referencedRelation: "broker_connections";
            referencedColumns: ["id"];
          },
        ];
      };
      positions: {
        Row: {
          id: string;
          user_id: string;
          broker_connection_id: string;
          tradingsymbol: string;
          exchange: string;
          segment: string;
          product_type: string;
          quantity: number;
          buy_quantity: number;
          sell_quantity: number;
          buy_average_price: number;
          sell_average_price: number;
          realized_pnl: number;
          unrealized_pnl: number;
          multiplier: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          broker_connection_id: string;
          tradingsymbol: string;
          exchange: string;
          segment: string;
          product_type: string;
          quantity: number;
          buy_quantity?: number;
          sell_quantity?: number;
          buy_average_price?: number;
          sell_average_price?: number;
          realized_pnl?: number;
          unrealized_pnl?: number;
          multiplier?: number;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          broker_connection_id?: string;
          tradingsymbol?: string;
          exchange?: string;
          segment?: string;
          product_type?: string;
          quantity?: number;
          buy_quantity?: number;
          sell_quantity?: number;
          buy_average_price?: number;
          sell_average_price?: number;
          realized_pnl?: number;
          unrealized_pnl?: number;
          multiplier?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "positions_broker_connection_id_fkey";
            columns: ["broker_connection_id"];
            referencedRelation: "broker_connections";
            referencedColumns: ["id"];
          },
        ];
      };
      trade_executions: {
        Row: {
          id: string;
          user_id: string;
          broker_connection_id: string;
          broker_execution_id: string;
          broker_order_id: string;
          exchange_order_id: string | null;
          tradingsymbol: string;
          exchange: string;
          segment: string;
          transaction_type: string;
          order_type: string;
          quantity: number;
          execution_price: number;
          execution_timestamp: string;
          brokerage_fee: number;
          stt_tax: number;
          exchange_turnover_fee: number;
          gst_fee: number;
          sebi_charges: number;
          stamp_duty: number;
          total_charges: number;
          fill_hash: string;
          raw_payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          broker_connection_id: string;
          broker_execution_id: string;
          broker_order_id: string;
          exchange_order_id?: string | null;
          tradingsymbol: string;
          exchange: string;
          segment: string;
          transaction_type: string;
          order_type: string;
          quantity: number;
          execution_price: number;
          execution_timestamp: string;
          brokerage_fee?: number;
          stt_tax?: number;
          exchange_turnover_fee?: number;
          gst_fee?: number;
          sebi_charges?: number;
          stamp_duty?: number;
          total_charges?: number;
          fill_hash: string;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          broker_connection_id?: string;
          broker_execution_id?: string;
          broker_order_id?: string;
          exchange_order_id?: string | null;
          tradingsymbol?: string;
          exchange?: string;
          segment?: string;
          transaction_type?: string;
          order_type?: string;
          quantity?: number;
          execution_price?: number;
          execution_timestamp?: string;
          brokerage_fee?: number;
          stt_tax?: number;
          exchange_turnover_fee?: number;
          gst_fee?: number;
          sebi_charges?: number;
          stamp_duty?: number;
          total_charges?: number;
          fill_hash?: string;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "trade_executions_broker_connection_id_fkey";
            columns: ["broker_connection_id"];
            referencedRelation: "broker_connections";
            referencedColumns: ["id"];
          },
        ];
      };
      journal_trades: {
        Row: {
          id: string;
          user_id: string;
          broker_connection_id: string;
          tradingsymbol: string;
          exchange: string;
          asset_class: string;
          direction: string;
          status: string;
          total_quantity: number;
          open_quantity: number;
          avg_entry_price: number;
          avg_exit_price: number | null;
          opened_at: string;
          closed_at: string | null;
          gross_pnl: number;
          total_fees_and_taxes: number;
          net_pnl: number;
          max_favorable_excursion: number | null;
          max_adverse_excursion: number | null;
          r_multiple: number | null;
          holding_period_minutes: number | null;
          trade_type: string | null;
          emotions: string[] | null;
          setup_playbook_id: string | null;
          rule_compliance_score: number | null;
          mistake_tags: string[] | null;
          trader_notes: string | null;
          audio_note_url: string | null;
          screenshot_urls: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          broker_connection_id: string;
          tradingsymbol: string;
          exchange: string;
          asset_class: string;
          direction: string;
          status?: string;
          total_quantity: number;
          open_quantity?: number;
          avg_entry_price: number;
          avg_exit_price?: number | null;
          opened_at: string;
          closed_at?: string | null;
          gross_pnl?: number;
          total_fees_and_taxes?: number;
          net_pnl?: number;
          max_favorable_excursion?: number | null;
          max_adverse_excursion?: number | null;
          r_multiple?: number | null;
          holding_period_minutes?: number | null;
          trade_type?: string | null;
          emotions?: string[] | null;
          setup_playbook_id?: string | null;
          rule_compliance_score?: number | null;
          mistake_tags?: string[] | null;
          trader_notes?: string | null;
          audio_note_url?: string | null;
          screenshot_urls?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          broker_connection_id?: string;
          tradingsymbol?: string;
          exchange?: string;
          asset_class?: string;
          direction?: string;
          status?: string;
          total_quantity?: number;
          open_quantity?: number;
          avg_entry_price?: number;
          avg_exit_price?: number | null;
          opened_at?: string;
          closed_at?: string | null;
          gross_pnl?: number;
          total_fees_and_taxes?: number;
          net_pnl?: number;
          max_favorable_excursion?: number | null;
          max_adverse_excursion?: number | null;
          r_multiple?: number | null;
          holding_period_minutes?: number | null;
          trade_type?: string | null;
          emotions?: string[] | null;
          setup_playbook_id?: string | null;
          rule_compliance_score?: number | null;
          mistake_tags?: string[] | null;
          trader_notes?: string | null;
          audio_note_url?: string | null;
          screenshot_urls?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "journal_trades_broker_connection_id_fkey";
            columns: ["broker_connection_id"];
            referencedRelation: "broker_connections";
            referencedColumns: ["id"];
          },
        ];
      };
      trade_execution_links: {
        Row: {
          id: string;
          journal_trade_id: string;
          execution_id: string;
          allocated_quantity: number;
          allocated_fees: number;
        };
        Insert: {
          id?: string;
          journal_trade_id: string;
          execution_id: string;
          allocated_quantity: number;
          allocated_fees?: number;
        };
        Update: {
          id?: string;
          journal_trade_id?: string;
          execution_id?: string;
          allocated_quantity?: number;
          allocated_fees?: number;
        };
        Relationships: [
          {
            foreignKeyName: "trade_execution_links_journal_trade_id_fkey";
            columns: ["journal_trade_id"];
            referencedRelation: "journal_trades";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "trade_execution_links_execution_id_fkey";
            columns: ["execution_id"];
            referencedRelation: "trade_executions";
            referencedColumns: ["id"];
          },
        ];
      };
      setup_playbooks: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          entry_criteria: string | null;
          exit_criteria: string | null;
          risk_rules: Json | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          entry_criteria?: string | null;
          exit_criteria?: string | null;
          risk_rules?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          entry_criteria?: string | null;
          exit_criteria?: string | null;
          risk_rules?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      admin_configs: {
        Row: {
          id: string;
          key: string;
          value: Json;
          type: string;
          label: string;
          description: string | null;
          category: string;
          is_public: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: Json;
          type: string;
          label: string;
          description?: string | null;
          category: string;
          is_public?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: Json;
          type?: string;
          label?: string;
          description?: string | null;
          category?: string;
          is_public?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      tax_rates: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          segment: string;
          transaction_type: string | null;
          rate_type: string;
          rate_value: number;
          applied_on: string;
          max_cap: number | null;
          min_amount: number | null;
          is_active: boolean;
          priority: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          segment: string;
          transaction_type?: string | null;
          rate_type?: string;
          rate_value: number;
          applied_on?: string;
          max_cap?: number | null;
          min_amount?: number | null;
          is_active?: boolean;
          priority?: number;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          segment?: string;
          transaction_type?: string | null;
          rate_type?: string;
          rate_value?: number;
          applied_on?: string;
          max_cap?: number | null;
          min_amount?: number | null;
          is_active?: boolean;
          priority?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      sync_logs: {
        Row: {
          id: string;
          user_id: string;
          broker_connection_id: string;
          sync_type: string;
          status: string;
          started_at: string;
          completed_at: string | null;
          executions_imported: number;
          trades_created: number;
          trades_updated: number;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          broker_connection_id: string;
          sync_type: string;
          status?: string;
          started_at?: string;
          completed_at?: string | null;
          executions_imported?: number;
          trades_created?: number;
          trades_updated?: number;
          error_message?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          broker_connection_id?: string;
          sync_type?: string;
          status?: string;
          started_at?: string;
          completed_at?: string | null;
          executions_imported?: number;
          trades_created?: number;
          trades_updated?: number;
          error_message?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "sync_logs_broker_connection_id_fkey";
            columns: ["broker_connection_id"];
            referencedRelation: "broker_connections";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
